# Generated by Django 5.2.9 on 2025-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', ' الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20),
        ),
    ]
